name: Docker Image CI for quizapp

on:
  push:
    branches: [ "main" ]  # Trigger this workflow on pushes to the main branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the Docker image
        run: |
          docker build ./app --file ./app/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/quiz-app-image:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/quiz-app-image:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/quiz-app-image:latest
        
      - name: Push the Docker image (version tag)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/quiz-app-image:${{ github.sha }}
      
      - name: Push the Docker image (latest tag)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/quiz-app-image:latest
